Applying styles
Hold-Krykke/3SemProject_FrontEnd pull request #40
Opened 2019-12-03 17:22 UTC by Castau

2019-12-06 18:25 UTC, Runi-VN approved these changes

2019-12-06 18:25 UTC, Runi-VN commented on src/App.js
> +    const [country, setCountry] = useState("Denmark");
This should be *reverted* before we merge :)  -- it was used to provide test data for the `Result` component.

2019-12-06 18:28 UTC, Runi-VN requested changes

2019-12-06 18:28 UTC, Runi-VN commented on src/App.js
> +    const [country, setCountry] = useState("Denmark");
This should be *reverted* before we merge :)  -- it was used to provide test data for the `Result` component.

2019-12-06 19:04 UTC, Runi-VN commented
# For reference 
*Before* vs. *after*
## Before
#### `App.js` or Map view (Frontpage)
![image](https://user-images.githubusercontent.com/37186286/70348507-1a485b80-1863-11ea-8cec-2ea588c2778f.png)
#### Zoomed in on country 
![image](https://user-images.githubusercontent.com/37186286/70348560-377d2a00-1863-11ea-997e-eeae01d032b2.png)
#### `Result.jsx` **event view**
![image](https://user-images.githubusercontent.com/37186286/70348628-60052400-1863-11ea-845d-f68255ff32a4.png)
#### `Result.jsx` **weather view**
![image](https://user-images.githubusercontent.com/37186286/70348682-80cd7980-1863-11ea-90ca-28f86c954b1f.png)

## After

2019-12-07 22:24 UTC, MrHardcode approved these changes

2019-12-07 23:00 UTC, Runi-VN commented on src/App.js
> +    const [country, setCountry] = useState("Denmark");
Fixed https://github.com/Hold-Krykke/3SemProject_FrontEnd/pull/40/commits/5c945c7918d0da54914977e1a0fa56edae47777a

2019-12-07 23:26 UTC, Runi-VN approved these changes
Added `target="blank"` to all URLs heading off-site (In the `About`, `Footer` & `Result` components) so that they open in a new tab.

I am very happy with the result.

2019-12-07 23:26 UTC, merged